services:
  auth-service-main:
    build: ./
    image: api-gateway-auth-service
    ports:
      - "8001:8001"
    env_file:
      - "./.env"
  auth-service-backup:
    build: ./
    image: api-gateway-auth-service
    ports:
      - "8002:8002"
    env_file:
      - "./.env"  
